### ISSUE TITLE
Support varint encoding

### ISSUE THREAD

**Issue by cBournhonesque** [SoftbearStudios/bitcode#12]

**Comment by finnbear** [comment]
We do support varint encoding, specifically gamma. See `#[bitcode_hint(gamma)]` via `#[derive(bitcode::Encode, bitcode::Decode)]`. Let us know if you want a different bit-wise varint encoding.

**Comment by cBournhonesque** [comment]
Oh you are right; I didn't notice it because there was no mention of bitcode-varint in this benchmark: https://github.com/SoftbearStudios/bitcode#primitives-size-in-bits
