### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by Ragarnoy** [SoftbearStudios/bitcode#15]
Could examples be included in this crate ?

**Comment by finnbear** [comment]
Good idea! For now, please see the examples in the docs: https://docs.rs/bitcode/latest/bitcode/

**Comment by Ragarnoy** [comment]
What about if say, I'm using heapless Strings or Vecs, how do you potentially encode those ?

**Comment by finnbear** [comment]
> What about if say, I'm using heapless Strings or Vecs, how do you potentially encode those ?

You have two options:
- Use the `serde` feature of `bitcode` and `heapless`, and use `bitcode::serialize` of `serde::Serialize` and `bitcode::deserialize` of `serde::Deserialize`
- Use the `#[bitcode(with_serde)]` attribute on fields of type `heapless::Vec<T: serde::Serialize>` or `heapless::String` (this is good if you only have a few such fields in a larger `T: bitcode::Encode`)

**Comment by Ragarnoy** [comment]
Thanks, is this crate able to be used in no_std ?

**Comment by finnbear** [comment]
We don't currently support `no_std` but we would probably accept a PR that cleanly adds support. Note that it is unlikely `bitcode` would work without `alloc` due to `Vec`.

**Comment by caibear** [comment]
An example was added to the README.md
