### ISSUE TITLE
Possible to remove dependency on `bitintr` crate?

### ISSUE THREAD

**Issue by djkoloski** [SoftbearStudios/bitcode#17]
`bitcode` no longer compiles on the latest nightlies because it depends on `bitintr` which uses the (now removed) `stdsimd` feature. I filed [an issue for `bitintr`](https://github.com/gnzlbg/bitintr/issues/19) detailing the issue. It looks like that crate hasn't been updated in a while, maybe it's worth removing the dependency altogether?

**Comment by finnbear** [comment]
Thank you for reporting this!

Here is a workaround you can apply immediately while we decide what to do in the long term:
```
# insert somewhere in your Cargo.toml
[patch.crates-io]
bitintr = { git = "https://github.com/finnbear/bitintr", branch = "remove_nightly" }
```

(the branch I made has [one commit to remove nightly issues](https://github.com/gnzlbg/bitintr/compare/master...finnbear:bitintr:remove_nightly))

**Comment by caibear** [comment]
`bitcode` uses `bitintr` for PDEP/PEXT x86 instructions to make `#[bitcode_hint(ascii)]` decoding/encoding about 2x faster. We could remove the `bitintr` dependency and have worse performance or remove `#[bitcode_hint(ascii)]` all together since it may not be that useful.

**Comment by finnbear** [comment]
We are removing `bitintr` as you suggested, with a 2X performance hit `#[bitcode_hint(ascii)]`.
