### ISSUE TITLE
Bitcode derive doesn't play well with other similarly named traits

### ISSUE THREAD

**Issue by udoprog** [SoftbearStudios/bitcode#2]
When I try to implement [bitcode benchmarks in Musli](https://github.com/udoprog/musli/pull/9), deriving `Encode` and `Decode` side by side with Musli traits does not work because Rust can't disambiguate the method call:

These are the kind of errors I'm getting.

```
error[E0034]: multiple applicable items in scope
  --> crates\musli-tests\src\models.rs:50:57
   |
50 | #[cfg_attr(feature = "bitcode", derive(bitcode::Encode, bitcode::Decode))]
   |                                                         ^^^^^^^^^^^^^^^ multiple `decode` found
   |
   = note: candidate #1 is defined in an impl of the trait `bitcode::Decode` for the type `HashMap<K, V>`
   = note: candidate #2 is defined in an impl of the trait `musli::Decode` for the type `HashMap<K, V, S>`
   = note: this error originates in the macro `dec` which comes from the expansion of the derive macro `bitcode::Decode` (in Nightly builds, run with -Z macro-backtrace for more info)
help: disambiguate the associated function for candidate #1
  --> C:\Users\udoprog\.cargo\registry\src\github.com-1ecc6299db9ec823\bitcode-0.4.0\src\code.rs:274:25
   |
274|                         <HashMap<alloc::string::String, u64> as bitcode::Decode>::decode($encoding, &mut buf.inner)?
   |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
help: disambiguate the associated function for candidate #2
  --> C:\Users\udoprog\.cargo\registry\src\github.com-1ecc6299db9ec823\bitcode-0.4.0\src\code.rs:274:25
   |
274|                         <HashMap<alloc::string::String, u64> as musli::Decode>::decode($encoding, &mut buf.inner)?
   |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

There are two ways to fix this:
* Do what it recommends - every time you call `::decode` or `::encode` through a type you make sure to disambiguate with an `<$ty as bitcode::Decode>::`.
* Use fully qualified method call syntax everywhere, like `bitcode::Decode::decode(/*  */)`. This is what I prefer and do in Musli.

**Comment by caibear** [comment]
Thanks for reporting this. I think I might have been able to fix it. Could you test it again with `bitcode = { git = "https://github.com/SoftbearStudios/bitcode" }`

**Comment by udoprog** [comment]
I'll give it a shot. I also sent you a repro in #3 you can try yourself ;)

**Comment by udoprog** [comment]
Cheers, I've now [included `bitcode` in my benchmark suite](https://github.com/udoprog/musli/pull/9).

**Comment by udoprog** [comment]
Heads up, but this has reared its head again:
![image](https://github.com/SoftbearStudios/bitcode/assets/111092/fe5caa59-b218-4dd8-be9e-f13f0c4232fa)

**Comment by finnbear** [comment]
@udoprog thank you. Turns out we haven't released a version in a while and:
1. I'm cautiously optimistic that this is fixed
2. Regardless, the line numbers in the error are way out of date

Please try `bitcode@0.5.0` (just released) and report back whether it works, or provide a new line number.

**Comment by udoprog** [comment]
Cheers, [bitcode will now be included](https://github.com/udoprog/musli/commit/ca739519ffd741529050da7b37ad82677a2640ad) in the next benchmarks I'm publishing.

**Comment by caibear** [comment]
> Cheers, [bitcode will now be included](https://github.com/udoprog/musli/commit/ca739519ffd741529050da7b37ad82677a2640ad) in the next benchmarks I'm publishing.

`bitcode@0.5.0` added 128 bit integer support so I think bitcode could be moved from the [fewer features](https://github.com/udoprog/musli/blob/main/benchmarks.md#fewer-features) section to full features.

I also noticed that you have [bitcode set to `default-features=false`](https://github.com/udoprog/musli/blob/ca739519ffd741529050da7b37ad82677a2640ad/crates/musli-tests/Cargo.toml#L74) which disables the `simdutf8` feature. I suspect this significantly impacts the results of the `dec/allocated` benchmark.
