### ISSUE TITLE
How to manually impl Encode?

### ISSUE THREAD

**Issue by PrismaPhonic** [SoftbearStudios/bitcode#22]
I'm trying to manually implement Encode and Decode for `Ulid`. In their library they manually impl for serde `Serialize` and `Deserialize` so it can live in a separate module, gated by a feature flag. 

To follow this design pattern, I can't use bitcode derive, and it appears that if I try to manually implement `Encode`, that the traits `Encoding` and `Write` are both in private modules that are no exported. I'm not seeing guidance in the docs for how one would manually implement Encode and Decode.

In this case I just need to call down to encode on the inner u128 (inside the Ulid, since it just wraps a u128), but can't put derive on the `Ulid` struct itself. What are my options?

**Comment by finnbear** [comment]
Hi, good question. If you are using bitcode `0.5` or below, simply enable the `serde` feature flag of `bitcode` and place `Ulid` in a struct or enum (including possibly a new type struct like `struct MyUlid(Ulid)`) and annotate that field with `#[bitcode(with_serde)]`.

e.g.
```rust
#[derive(Encode, Decode)]
struct MyStruct {
    field1: usize,
    #[bitcode(with_serde)]
    field2: Ulid,
}
```
or (for modularity)
```rust
#[derive(Encode, Decode)]
struct MyUlid(#[bitcode(with_serde)] Ulid);

impl From<Ulid> for MyUlid { ... }
impl From<MyUlid> for Ulid { ... }
impl Deref for MyUlid { type Target = Ulid; ... }
```

If you are using `0.6` beta, there is not currently a way to do it yourself. The implementation either has to be in `bitcode` or `ulid`. If you want, we'll consider adding it to `bitcode`.

**Comment by finnbear** [comment]
We do have specific guidance for adding `bitcode` to libraries: https://github.com/SoftbearStudios/bitcode?tab=readme-ov-file#library-example

One issue is that `ulid` is version `1.1.2`, in other words stable. It's unlikely/impossible for them to depend on an unstable crate, `bitcode`.

By the way, for completeness, I should mention that you can use `bitcode` via serde (`bitcode::{serialize, deserialize}` on the `serde` feature flag). Then library support becomes a non-issue. It's just moderately slower and slightly larger.
