### ISSUE TITLE
Should it be able to encode into base64-esque alphabet without padding?

### ISSUE THREAD

**Issue by vi** [SoftbearStudios/bitcode#4]
Shall `bitcode` have something like a 6-bit byte mode where it outputs not arbitrary `u8` values, but only those bytes that represent one of 64 variants.

It should work somewhat like `base64::encode(bitcode::encode(&x))`,  but without the padding, fitting 6-bit things into one character instead of two as in sample above (or even four if padding is used) for easy input.

---

Related idea: encoding into `FnMut(bool)` and decoding from `FnMut()->bool`.

**Comment by caibear** [comment]
> It should work somewhat like base64::encode(bitcode::encode(&x))

I think it would be quite hard to beat the performance of `base64::encode(bitcode::encode(&x))` even though it's two separate operations, therefore I don't see the point in implementing this in bitcode. Also there are other options people might want such as base85.

> but without the padding, fitting 6-bit things into one character instead of two as in sample above (or even four if padding is used) for easy input.

Maybe we could expose a method to tell you how many bits were serialized so you could implement this outside bitcode. I'm thinking something like:
```rust
use bitcode::Buffer;

let mut buffer = bitcode::Buffer::new();
let bytes: &[u8] = buffer.encode(&[true, false, true, false]).unwrap();
let bits: usize = buffer.encoded_bits();
assert_eq!(bytes, 1);
assert_eq!(bits, 4);
```

**Comment by vi** [comment]
> encoded_bits

Nice idea.

It should specify whether high or low bits of the buffer are used.

**Comment by caibear** [comment]
> It should specify whether high or low bits of the buffer are used.

Maybe, currently low bits are always used first.

**Comment by caibear** [comment]
I have to work out what should happen if you call `buffer.encoded_bits()` after you deserialize or before you've done anything with the buffer. Also if it returns a usize, this would limit serialization to 0.5GB on 32 bit.

**Comment by caibear** [comment]
After further consideration I don't think a new API is actually required to encode base64 without padding.
```rust
let bytes: Vec<u8> = bitcode::encode(&[true, false, true, false]).unwrap();

let encoded_bits: usize = bytes.last().map_or(0, |last_byte| {
    // Between 1 and 8, can't be zero because decoding needs to reproduce length in bytes.
    (8 - last_byte.leading_zeros()).max(1) as usize
}) + bytes.len().saturating_sub(1) * 8;
``` 
When decoding you just have to ensure that the remaining bits of the last u8 are zeros.

**Comment by vi** [comment]
Shall it be officially documented that zeroes are really leading, not trailing to be able to rely on that?

**Comment by caibear** [comment]
> Shall it be officially documented that zeroes are really leading, not trailing to be able to rely on that?

It's highly unlikely that we will change to trailing zeros. In the worst case if we did change, you would get an extra byte of padding (but that code would continue to work). I'm not sure if documenting that fact really makes sense considering that we make no guarantees about the bitcode format except that we will bump the major version whenever it changes. Maybe we could document that this is how it currently works.
