### ISSUE TITLE
JavaScript implementation

### ISSUE THREAD

**Issue by MrFoxPro** [SoftbearStudios/bitcode#48]
Hello. I recently re-implemented encoder for `bincode` format in TypeScript https://github.com/zefchain/serde-reflection/blob/b9ae2d55db51079bde5e7c9ff217aad0136d3fbd/serde-generate/runtime/typescript/serde.ts. 
I'm wondering if it's possible to make same adapter for `bitcode`? Maybe you can give some directions?

**Comment by finnbear** [comment]
I recommend compiling `bitcode` to WebAssembly. You can inline base64 WebAssembly into your JavaScript if needed. `bitcode` is too complex/unstable for porting to JavaScript to be realistic. Good luck!
